package Advent;

import java.util.ArrayList;

public class BinaryBoarding {
    public static void main(String[] args) {
        String in = "FBFBFFBLLR\n" +
                "FBBBFFBLLL\n" +
                "BFBFFFFRRR\n" +
                "BFBBBFBRLL\n" +
                "FBFBBFBLLL\n" +
                "BBBFFFBRRR\n" +
                "FBFFFBFRRL\n" +
                "BFFFFFFRLR\n" +
                "FBFFBBFRRL\n" +
                "FBFBBFBRLL\n" +
                "BFBBBFBRRR\n" +
                "BBFBFFBRLL\n" +
                "FBBFBFFLLL\n" +
                "FBBFFFBRLR\n" +
                "BBFFFFBLRL\n" +
                "FFFBBBBRLR\n" +
                "FFBBBFBRLL\n" +
                "FBBBFBFLLL\n" +
                "FBBBFFFRLL\n" +
                "FBBFBBFLRR\n" +
                "FBFBBBBLLL\n" +
                "BBFBFBFLRR\n" +
                "FBFFFBFRLR\n" +
                "FFFBBFBLLL\n" +
                "FBFFBBBRLL\n" +
                "FBBBFBFLRL\n" +
                "BFFFBFBRRL\n" +
                "BFFBFFBLRR\n" +
                "BBFBBBBRRL\n" +
                "FBFBBBBRRR\n" +
                "BBBFFBBLRL\n" +
                "BBFBFFFRRR\n" +
                "FFBBBBBRRL\n" +
                "BFFBBFFLLR\n" +
                "BBFFFFBRRR\n" +
                "FBFBFFFRLL\n" +
                "FFFBFBBLLL\n" +
                "FBBFBFBLRR\n" +
                "FBFBFBFLLL\n" +
                "BFFFFFFLRR\n" +
                "BFFBBFFRLL\n" +
                "FFBFBBFLLL\n" +
                "FBFBBBFRLL\n" +
                "BFFFFFFLLR\n" +
                "FFFBFBFRLR\n" +
                "FBFFFFBLLL\n" +
                "FFBFBBBLLL\n" +
                "BBFFBBBLRL\n" +
                "BBFBBBBLRR\n" +
                "BFBFBFFRLL\n" +
                "FFFBFBBRLL\n" +
                "FBBBFBBRLL\n" +
                "FBFFFFFLRR\n" +
                "BFFBFBBRLR\n" +
                "BFFBBBBRRR\n" +
                "FBBBBBFLRR\n" +
                "BFFFBFFRRL\n" +
                "FBFBFFFLLR\n" +
                "FBBBFBBRRL\n" +
                "FFBFBBBLRR\n" +
                "FFBFBFBLRR\n" +
                "BFFFBFBLRL\n" +
                "BFFBFBBLRR\n" +
                "BFFFFFBLLR\n" +
                "FBFFBBBRRL\n" +
                "BFFBFFFLLR\n" +
                "BBBFFFFRRL\n" +
                "FBBFBBBRRR\n" +
                "FBFBBBFLLL\n" +
                "FBBFFBFRRR\n" +
                "FFBFFFBLRR\n" +
                "BFFFFBBRRL\n" +
                "FBBBFBFRLL\n" +
                "FFBBFFFLLL\n" +
                "BBFFFFFRLL\n" +
                "BFFBFFBRLR\n" +
                "FFBFFBFRRL\n" +
                "FBBFFFBLLR\n" +
                "FFFBFBFLRR\n" +
                "BFBFBBBRLR\n" +
                "BFBFFBFLLR\n" +
                "FFFBBFBRLR\n" +
                "FFFBBBFLLL\n" +
                "BBFFFFBRLR\n" +
                "FFBBFFFLRR\n" +
                "BBBFFBFLLR\n" +
                "FBFBFFFRRR\n" +
                "BBFFBFBRLL\n" +
                "FBFBFFFLRR\n" +
                "FBBFBFBRRR\n" +
                "FBBFBFFLRR\n" +
                "BFBFFFBRRR\n" +
                "BFBFFFBRLR\n" +
                "BFFBBBFRRL\n" +
                "BBFFBBBLLL\n" +
                "BFBFFBFRRL\n" +
                "BFBFFFFLLL\n" +
                "BFBFFFBLLL\n" +
                "FBFFFFFRRL\n" +
                "FFBFFBBLLL\n" +
                "BFFBFFBLRL\n" +
                "BFFBFBBLLR\n" +
                "FBBFFFBLLL\n" +
                "BFFFBFBLLR\n" +
                "FFFBBBFLRR\n" +
                "BFBFBFFLRR\n" +
                "FBBFFFFRLR\n" +
                "FBFBBFFLLR\n" +
                "FBFFBFBRRL\n" +
                "FBBFFBFLLR\n" +
                "FBFBFBBLRL\n" +
                "FFFBFFBRLL\n" +
                "BBFBBBFRLL\n" +
                "FFBFBBBRLL\n" +
                "BBBFFFBLLR\n" +
                "BFBBBFBLRL\n" +
                "BFBFFFFLRR\n" +
                "FFBFBFFRLR\n" +
                "FBFBFFBRLL\n" +
                "FFBFFFFLLR\n" +
                "FBFFBFFLRL\n" +
                "FFFBFFBLLR\n" +
                "FFFBFBFRRR\n" +
                "BFBBFBBRRR\n" +
                "BFFBBBFLLL\n" +
                "BFFFBBBRRR\n" +
                "BFBBBFFRRR\n" +
                "BBBFFFFRLL\n" +
                "BFBBBFBLLL\n" +
                "FFFBFBFLRL\n" +
                "FFBBFBFRRR\n" +
                "FFBBFBFRLR\n" +
                "BFBBBBBRLR\n" +
                "BBBFBFFLLR\n" +
                "FFBBBBFLLL\n" +
                "BFBFBBFRLL\n" +
                "BFBFBBBRRL\n" +
                "BFBBBBBLRL\n" +
                "BFFBBFBRRR\n" +
                "FBFFFFFRLR\n" +
                "BFFBFBFRRL\n" +
                "BFFBBFBLLR\n" +
                "FBBFFBFRRL\n" +
                "BFFFBFBRLR\n" +
                "BBFFBFFRRL\n" +
                "FBFFBBFRLL\n" +
                "FFBFFFBRLL\n" +
                "BBBFFFBRRL\n" +
                "BFBFFBFLLL\n" +
                "FBFBBFBRRL\n" +
                "FFFBBFFRRR\n" +
                "BBFBFFBLRR\n" +
                "BBBFFFBLRL\n" +
                "BFFFBBBLRL\n" +
                "FBFFFBBLLR\n" +
                "FBBFBBBRRL\n" +
                "FBFBBFBRLR\n" +
                "BFBFFFBRRL\n" +
                "FBBFBFBLRL\n" +
                "FFBBBFBLLL\n" +
                "FFBBBFFRRL\n" +
                "FFBFFBFRLL\n" +
                "FBFBBBFRRL\n" +
                "BFBFBBFLLL\n" +
                "FFBFFBFLLL\n" +
                "FBBBBFBLLL\n" +
                "FFBFBFFRRR\n" +
                "FBBFFBFLRR\n" +
                "BBFFFFBLLL\n" +
                "FBFFFFFRRR\n" +
                "BFFBBBFLLR\n" +
                "FFFBFFFRRL\n" +
                "BBFFFBBRRR\n" +
                "FFBFFBBLLR\n" +
                "FBFBFBFRRL\n" +
                "BFBFFBBRLL\n" +
                "FFFBBBFRLR\n" +
                "FFBFFFFRRL\n" +
                "FBBBFFBLRL\n" +
                "BFFBBFBRLR\n" +
                "FBFBBBFRLR\n" +
                "FFFBFFBLRL\n" +
                "BFFFFFBRLR\n" +
                "FBFFBBBRLR\n" +
                "BBBFBFFRLL\n" +
                "BBFFFBFRLR\n" +
                "FFBFBBFRLR\n" +
                "BFFFBBFLLR\n" +
                "BBFBFBFLLL\n" +
                "BBBFFBBLLR\n" +
                "BFFFFBBLLR\n" +
                "BBFBBBBRLR\n" +
                "FBFFFBFRLL\n" +
                "BFBBFBBLRL\n" +
                "FBFBFFBRLR\n" +
                "FBBFFFBRRL\n" +
                "BFBFFFFRRL\n" +
                "FFBFFFBLRL\n" +
                "BBFBBFBRLL\n" +
                "BFFFFFBLLL\n" +
                "BBBFFBFLLL\n" +
                "FBFBBBBLLR\n" +
                "BBFFFBFLLL\n" +
                "BFFBFBFLRR\n" +
                "BBBFBFFLRL\n" +
                "FFBFBFFRLL\n" +
                "FBBFFFFLLL\n" +
                "FFBBFBBRRR\n" +
                "BFBFFFBLRR\n" +
                "BFFBFBBRRL\n" +
                "BBFBBBFLRL\n" +
                "BFBBFBFLLL\n" +
                "BFBBBBFRLR\n" +
                "BBFBBFFLLL\n" +
                "BBFFBBFRLL\n" +
                "FBBBBFBRLR\n" +
                "FBBBBBFRLR\n" +
                "BFFFFBFRLR\n" +
                "BFFFFFFRRL\n" +
                "FBBFBFFRRR\n" +
                "FFBFFBBLRR\n" +
                "BBBFFFBRLR\n" +
                "FFFBBFFLLR\n" +
                "BBFBBFBRRR\n" +
                "FFBBFBFRRL\n" +
                "FBFFFFBRRR\n" +
                "FBBBBBBRRL\n" +
                "BBFBFFBRLR\n" +
                "BBBFFBBLLL\n" +
                "BFFBFBFLRL\n" +
                "BFFFFBBLRR\n" +
                "BFFBBFBLRL\n" +
                "BFBBFBFRRL\n" +
                "BFBFBBBLRR\n" +
                "FBBFFFBRRR\n" +
                "FFFBBBBLLR\n" +
                "BBFBBBBRRR\n" +
                "FFBFFBFLRL\n" +
                "BFBFBBFRRR\n" +
                "BFBFBFFRRR\n" +
                "FBBFFFFRRL\n" +
                "FFFBFBFRLL\n" +
                "BBFFFFFLLL\n" +
                "BBFBBBFRRR\n" +
                "FFBBBFFRLL\n" +
                "FBBFBFFRLR\n" +
                "BFFFFFBRRR\n" +
                "BFFFBFFRRR\n" +
                "BBBFFBFRRL\n" +
                "BFFBBFFLRL\n" +
                "FBFFBFBRRR\n" +
                "BFBBFFBRLL\n" +
                "BFFFBBBRLR\n" +
                "FFBBFBFLRR\n" +
                "FBFFBBBLRL\n" +
                "BBFFBFFRLL\n" +
                "FFFBFFFRRR\n" +
                "FBFBFFFRLR\n" +
                "FFBFBFFLRR\n" +
                "BBFFBFBLRR\n" +
                "BBFFFBBRLL\n" +
                "BFBFBBFLRL\n" +
                "FBFFBBFRLR\n" +
                "BFFFBFBLLL\n" +
                "FBFFBFFRRL\n" +
                "FBBBBBFRRR\n" +
                "FBFFBBFLLR\n" +
                "BFBBFBBRLR\n" +
                "FBBFBBBLLL\n" +
                "BBBFBFBLLL\n" +
                "BFBFBFBLLR\n" +
                "BFFFFBBLRL\n" +
                "BBFBFBBLLR\n" +
                "BBFFFBBLRR\n" +
                "BBFFBFFRRR\n" +
                "BFFFFFFRRR\n" +
                "FBFBFBBRRL\n" +
                "BFBFFBFLRL\n" +
                "BFBBBBBLLR\n" +
                "BBBFFFFLLR\n" +
                "FBFFBFFLRR\n" +
                "BFFFBFFRLL\n" +
                "FFBFBBFLRR\n" +
                "BFFBFBFLLR\n" +
                "FBFFFBFLLL\n" +
                "FFBBFFBLLR\n" +
                "BBFBFBFRLR\n" +
                "FBFBBFFRLR\n" +
                "BFBBBBFLLR\n" +
                "FFBFBFFLRL\n" +
                "BFBBBBFLLL\n" +
                "BFFFBFFRLR\n" +
                "FBFFFBBLLL\n" +
                "FFBFBFBRLL\n" +
                "FBFBFFBRRR\n" +
                "BFBBFBFLRL\n" +
                "FFFBBBBRRL\n" +
                "FFBFBBBRRR\n" +
                "BFFBBFFRLR\n" +
                "FBFBBFFLRR\n" +
                "FBFFFBBRRR\n" +
                "BFBBFFFRLR\n" +
                "FFBFFFBRRR\n" +
                "FFBFFFBLLR\n" +
                "BFBFFFBLRL\n" +
                "FBFBFBBRLL\n" +
                "FBBBFBBRRR\n" +
                "BBFFBFBRLR\n" +
                "BFFFBBFRLL\n" +
                "FBFBFBFLLR\n" +
                "FFBFFBBRRR\n" +
                "BFBFBBFLRR\n" +
                "FFBBFBBLLR\n" +
                "FFBFFFBRLR\n" +
                "FFFBBBBLLL\n" +
                "BBBFFBFRRR\n" +
                "FBBFBBFLLR\n" +
                "BFBBBFFRRL\n" +
                "FBBBBFFLRL\n" +
                "BFBFBBBLRL\n" +
                "FFBFBBFLLR\n" +
                "BFFFBFBRLL\n" +
                "BFFBFFFRRL\n" +
                "BFFBFFFRLL\n" +
                "FFBBFBBLLL\n" +
                "BBFFFBFRRL\n" +
                "BBFBFBFRRR\n" +
                "FBFBBFFRRL\n" +
                "BFBBFBBLLL\n" +
                "FBFFBFFLLR\n" +
                "FBBBBFFRLR\n" +
                "FBFFBFBRLL\n" +
                "FFBBBBFRRR\n" +
                "FBBBBFBRRR\n" +
                "FBFBBBFLRR\n" +
                "FBBFBFBLLR\n" +
                "FBBBFBFLRR\n" +
                "FBFFBBFLLL\n" +
                "BFBFFFBLLR\n" +
                "FBFFFFBLRR\n" +
                "BFBBBFFLRR\n" +
                "BFBFBBFRLR\n" +
                "FBBFFFBLRL\n" +
                "FBBBBFFRLL\n" +
                "BBBFBFFRRL\n" +
                "BFBFBBBRLL\n" +
                "FFFBBBFLLR\n" +
                "FBBBBBFLLR\n" +
                "BFBFBBFLLR\n" +
                "BFBFBBBRRR\n" +
                "BFBBFBBRLL\n" +
                "FBFFFFBRRL\n" +
                "BBFBFBBRRR\n" +
                "FFBFBFBRRR\n" +
                "FFBFBBFRRL\n" +
                "BBFFFFBRLL\n" +
                "BFFBBBFRLL\n" +
                "FBBBFFBLLR\n" +
                "BFBFBFBRLL\n" +
                "FBBFFBBRLL\n" +
                "FBFFFBBRLR\n" +
                "BBFFBBBRRR\n" +
                "FBBBBBBRRR\n" +
                "FBBFBBFRRL\n" +
                "BFFFBBFLRL\n" +
                "FFFBFBBLRR\n" +
                "FBBBBBBLLL\n" +
                "FFFBFBBRRL\n" +
                "BBBFFFFRRR\n" +
                "BFFFBFFLLL\n" +
                "FFFBFBBLLR\n" +
                "FBFFBBFLRL\n" +
                "BFBBFFFRLL\n" +
                "BBFBFBBLLL\n" +
                "FBBBFFFLRR\n" +
                "BFFBFFBLLL\n" +
                "FBBFBFBRLL\n" +
                "BFBBFFFLLR\n" +
                "FBBFFFBLRR\n" +
                "BFFBBBBLLL\n" +
                "BBFFFBFRRR\n" +
                "FFBBBBFLRL\n" +
                "FBBFFFFLRL\n" +
                "FFFBFBFLLR\n" +
                "BFBBBFBRRL\n" +
                "FFFBBBFRRR\n" +
                "FBBBFBFRLR\n" +
                "BFBFBFFRLR\n" +
                "BFBFFBBLLR\n" +
                "FBFFBFBRLR\n" +
                "BBFBFFFLRL\n" +
                "FBBBFBBLLR\n" +
                "FFBFFBBRLL\n" +
                "FBFFFBBRLL\n" +
                "BFFFFFBRLL\n" +
                "BFFBBBBLLR\n" +
                "FFBBBBFRLL\n" +
                "FFBBBFBRRR\n" +
                "FBBBFBBLLL\n" +
                "FBBBFFBRRL\n" +
                "FFBBBBBLRR\n" +
                "BBFBBBFLRR\n" +
                "BBFBBFFLRL\n" +
                "BBFFBBBRLR\n" +
                "FBFBFFFRRL\n" +
                "BFBFFBBRRL\n" +
                "BBFBBBBRLL\n" +
                "BFFBBBBRRL\n" +
                "BBFBBFFRLR\n" +
                "BFFBBFBLLL\n" +
                "FBBBBBBRLR\n" +
                "FBBFBBBLRL\n" +
                "FFBFFBFRRR\n" +
                "FFFBFFBLRR\n" +
                "BFBBBFBLRR\n" +
                "FFBBFFBRRR\n" +
                "FFFBBBBRRR\n" +
                "FBFFBBBLRR\n" +
                "BFBFFBBLRL\n" +
                "FFBBBBBRLL\n" +
                "BBFBFFBRRR\n" +
                "FFBBFFBLLL\n" +
                "BBFBBFBLLL\n" +
                "BFBFBBBLLR\n" +
                "FBBBFBBRLR\n" +
                "BFBBFFFLRL\n" +
                "BFBBFFFLLL\n" +
                "BFBBFBFRLL\n" +
                "FBFFFFBRLR\n" +
                "FBBFFFFRLL\n" +
                "FFBFBFFLLR\n" +
                "BFFBFBFRRR\n" +
                "BFFBBFBRLL\n" +
                "BFBFBFBRRR\n" +
                "FBFFBFFLLL\n" +
                "FBBFBBFLLL\n" +
                "BBFBBBFLLL\n" +
                "BBFBBFFRLL\n" +
                "BFFFBFFLRR\n" +
                "FBFFFBFRRR\n" +
                "FBBBBFFLRR\n" +
                "FFBBBBBLLL\n" +
                "BFBBBBFRLL\n" +
                "FBBFFBBRRL\n" +
                "FFBFFBBRLR\n" +
                "BFBFBFBRLR\n" +
                "FFBFBBFLRL\n" +
                "FFBBBFBLRL\n" +
                "BFFBBFFLRR\n" +
                "FBFBFBBRRR\n" +
                "FBFBBFBLRL\n" +
                "FBFFFFBLLR\n" +
                "FFBBBBFLRR\n" +
                "FBFBBBBLRL\n" +
                "FFFBBFFRLR\n" +
                "BBBFFBFRLR\n" +
                "FFFBBFBRRR\n" +
                "FFBFFFFRLR\n" +
                "BFFBFFBRRL\n" +
                "FBFBFFFLRL\n" +
                "FFBFBFBLRL\n" +
                "FBBBFBBLRR\n" +
                "BFFFFBFRRL\n" +
                "FBFFFBBLRL\n" +
                "FFFBBBFRLL\n" +
                "BFFBBFFLLL\n" +
                "FFFBFBBRLR\n" +
                "FBBFBBFLRL\n" +
                "BFFFFFFLLL\n" +
                "FFFBBFFLRR\n" +
                "FFBFFBFLRR\n" +
                "FFBBBBFLLR\n" +
                "BFFFBFFLLR\n" +
                "FBBFBBBLRR\n" +
                "BBBFFBFLRR\n" +
                "FBBFFBBLRL\n" +
                "FBFBBBBRRL\n" +
                "BBFFBBFLLR\n" +
                "BBBFFBFRLL\n" +
                "FBFFFFBLRL\n" +
                "BBBFBFFRLR\n" +
                "BBFFBBFLRL\n" +
                "BFBFBFBLLL\n" +
                "FFBFBBFRRR\n" +
                "BFBBBFFLLR\n" +
                "FBBFFFFLRR\n" +
                "BFBFFFFRLL\n" +
                "FBFFBBBLLL\n" +
                "BBFFFFFLRL\n" +
                "BFFBFBFLLL\n" +
                "BBFBBBFRRL\n" +
                "FBFFFBFLRL\n" +
                "BFFFBBBLLL\n" +
                "FFBBBFFLLL\n" +
                "BBFFFFFRRL\n" +
                "FBBFFBFLRL\n" +
                "FBBBFBBLRL\n" +
                "FFBBFBFRLL\n" +
                "FFBFBBFRLL\n" +
                "BBFFFBBRLR\n" +
                "FBFBBFBLLR\n" +
                "FBFFBBBRRR\n" +
                "FBFFFFFLRL\n" +
                "BBFBBBBLLR\n" +
                "FFBBBFFLRL\n" +
                "BFBBBBFRRR\n" +
                "FBBBBBFRLL\n" +
                "FFBBFFBRRL\n" +
                "FBBBFFBLRR\n" +
                "BFBFFBFRLR\n" +
                "FBFFFBFLRR\n" +
                "FBFBFFBLRL\n" +
                "FBFBFBFRLL\n" +
                "BBFBFFFLLR\n" +
                "BFBBFFBLRR\n" +
                "FFFBFFBRRR\n" +
                "BBFFBFFLLR\n" +
                "BFFBFBFRLL\n" +
                "BFBBFBFRLR\n" +
                "BBFFFFBLRR\n" +
                "BBFFFFFRRR\n" +
                "FFFBBFFRLL\n" +
                "BFFBFFFLRR\n" +
                "BFBBBBBRRL\n" +
                "FBBBFFBRLL\n" +
                "BFFFBFBRRR\n" +
                "FFFBFFBRLR\n" +
                "FBBFBBBRLR\n" +
                "BFFFFFBLRL\n" +
                "BFBFFBFLRR\n" +
                "FBFBBFBLRR\n" +
                "FFBFBFBLLL\n" +
                "BBFBFBBRRL\n" +
                "FBBBBFBLRR\n" +
                "FBFBBBFLLR\n" +
                "FBFBFFBLRR\n" +
                "BBFBFBFLLR\n" +
                "BBFFBFBLLL\n" +
                "FFBBFFBRLR\n" +
                "FFBFBFFRRL\n" +
                "FBFBBBBRLR\n" +
                "BBFBBFFRRL\n" +
                "FFBBBBBRRR\n" +
                "BBFBFFBLLL\n" +
                "BFFBBFFRRR\n" +
                "BFBBFBFLLR\n" +
                "FFBFFBBRRL\n" +
                "BFFBBFBRRL\n" +
                "FFBFFFFRLL\n" +
                "BFFBFFBRRR\n" +
                "BFFFBFBLRR\n" +
                "BFFFFFBLRR\n" +
                "FFBBFFFLRL\n" +
                "FBFBBFBRRR\n" +
                "FBFBFBBRLR\n" +
                "BBFBFBFRLL\n" +
                "BFFBBBFLRL\n" +
                "BBFBBBFRLR\n" +
                "BBFBFBBLRL\n" +
                "FBBBFFBRRR\n" +
                "FBBFFBFRLL\n" +
                "FBBBBBFLRL\n" +
                "FBBFFBBLLR\n" +
                "FBFBBFFRRR\n" +
                "FBFBBBBRLL\n" +
                "FFBFBBBRLR\n" +
                "FBBBBFFLLL\n" +
                "BFBBFFBLRL\n" +
                "BBFBFBBRLR\n" +
                "FFBBFFBLRR\n" +
                "FFBFFFFRRR\n" +
                "FFBFBFFLLL\n" +
                "BFFFBBFRRR\n" +
                "FBBFBBBLLR\n" +
                "BFFFBBFRLR\n" +
                "BFFFFBFLLL\n" +
                "BBFFFBFLLR\n" +
                "FBFFFFFLLL\n" +
                "BBBFFFBLLL\n" +
                "BBBFFBBRRL\n" +
                "BFFBBBBRLL\n" +
                "BFBFFFFRLR\n" +
                "FBBBFFFRLR\n" +
                "BBFBFFFRLL\n" +
                "FFBBFFFRLL\n" +
                "BFBBFFBRRL\n" +
                "BBFFBBBLRR\n" +
                "BBBFFBBRRR\n" +
                "FFFBBFBRRL\n" +
                "FFBFFFFLRL\n" +
                "BFBBFBBLRR\n" +
                "FFFBFBBLRL\n" +
                "FBFFBFBLLL\n" +
                "FBFBBBBLRR\n" +
                "BFBBBFFLLL\n" +
                "FFBBFBBRRL\n" +
                "BBBFFFFLRR\n" +
                "BBFFFFFRLR\n" +
                "BBBFFFBRLL\n" +
                "BBBFFFFLRL\n" +
                "FFBBBFBRRL\n" +
                "FFBFFFBRRL\n" +
                "BFFBBBFLRR\n" +
                "FFFBBFBLLR\n" +
                "BFBBFBBRRL\n" +
                "FBBBBFFRRR\n" +
                "FBFBFBFLRR\n" +
                "BBFBBFBRLR\n" +
                "BBFFBBFRLR\n" +
                "BBFBFFFRRL\n" +
                "FBFBBBFLRL\n" +
                "BFFFFBBRLR\n" +
                "FBBBFFFRRR\n" +
                "BBFFBBFLRR\n" +
                "BFFFBBFLRR\n" +
                "FFBBFBFLLL\n" +
                "FFBBBBBLLR\n" +
                "BFFBFFBRLL\n" +
                "BFFBFFFRRR\n" +
                "BBFBFBFRRL\n" +
                "BFBFFBBRLR\n" +
                "BBBFBFFRRR\n" +
                "FBFFBFBLRR\n" +
                "FFFBBFFLRL\n" +
                "FBFBFBFRLR\n" +
                "BFBFFFFLRL\n" +
                "BBFFFFBLLR\n" +
                "FFBFBBBRRL\n" +
                "BBFBBFBLLR\n" +
                "BFFBFBBLLL\n" +
                "BFBBBFBLLR\n" +
                "BFBBFFFRRR\n" +
                "BFFFBBFLLL\n" +
                "FFBBFFFLLR\n" +
                "FBFFFBBLRR\n" +
                "BFBFBFBLRR\n" +
                "BFBBFBFLRR\n" +
                "BFFFBBBLRR\n" +
                "FBFBBFFLLL\n" +
                "BFBBBBBRLL\n" +
                "BFBFBFBRRL\n" +
                "BBBFFFBLRR\n" +
                "BBFFFFBRRL\n" +
                "BBFBFFBLRL\n" +
                "FFBBBFBLRR\n" +
                "FBBFBFFRLL\n" +
                "FFBBFBBLRL\n" +
                "FBBFFFBRLL\n" +
                "BBBFBFFLRR\n" +
                "FFFBFFBLLL\n" +
                "BFBBBBBLLL\n" +
                "BBFFFFFLLR\n" +
                "FBFBFFFLLL\n" +
                "BBFBBFBLRL\n" +
                "BFBFFBBLLL\n" +
                "BBFBBBBLRL\n" +
                "FBBBBFBRRL\n" +
                "BFFBFBBRRR\n" +
                "FBFBBBFRRR\n" +
                "BFFBBBFRRR\n" +
                "BFFFBBBLLR\n" +
                "FFBBBBFRLR\n" +
                "BFBFFBFRRR\n" +
                "FBFBFBFRRR\n" +
                "FFFBFBBRRR\n" +
                "BFBFFFFLLR\n" +
                "FBBBBBBLRL\n" +
                "BFFFFBFLRL\n" +
                "BFFFFFFLRL\n" +
                "BFFFBBBRLL\n" +
                "BFFFFBBRLL\n" +
                "FBBFFFFRRR\n" +
                "BBBFFBBRLL\n" +
                "BFBBFFBLLL\n" +
                "FFFBBFBLRL\n" +
                "FBBBFBFLLR\n" +
                "BFFBFBBLRL\n" +
                "BBBFBFBLRL\n" +
                "BBFBFFFLRR\n" +
                "BBFBFFBRRL\n" +
                "BFBFBFBLRL\n" +
                "FBBBBFBRLL\n" +
                "BBFBBFBRRL\n" +
                "BBFFBFBLRL\n" +
                "FBBBBBFRRL\n" +
                "FBBFBFBLLL\n" +
                "FFBBFFBRLL\n" +
                "BBFFFBBLLL\n" +
                "BFFFBBFRRL\n" +
                "BBFBBFFRRR\n" +
                "FBBBBBBLRR\n" +
                "FFBBBFBRLR\n" +
                "BFFFFFBRRL\n" +
                "FBFFFFFRLL\n" +
                "BBFFBFFRLR\n" +
                "BBFFBFBLLR\n" +
                "BBFFBFBRRL\n" +
                "BBBFFFFRLR\n" +
                "BBFFBFFLRR\n" +
                "FFBBFFFRRL\n" +
                "BFFFBBBRRL\n" +
                "BBBFFFFLLL\n" +
                "BBFBFFBLLR\n" +
                "BBFBBFFLLR\n" +
                "FFBBBBFRRL\n" +
                "FBFBFBBLLR\n" +
                "FFFBBBBLRL\n" +
                "BFBFFFBRLL\n" +
                "FBFFBFFRLL\n" +
                "FBBFFBFRLR\n" +
                "BFFFFBFLLR\n" +
                "FBBBBBFLLL\n" +
                "BBFBBBFLLR\n" +
                "FBBBBFBLLR\n" +
                "FBFFBBBLLR\n" +
                "BBFFBBFRRL\n" +
                "FFBBBFBLLR\n" +
                "FBFFBFBLRL\n" +
                "FBFFFFBRLL\n" +
                "BFBFFBFRLL\n" +
                "FFBBFBFLRL\n" +
                "FBBFFBFLLL\n" +
                "BBFBBFFLRR\n" +
                "FFBFFBFRLR\n" +
                "BFFFFBFLRR\n" +
                "BFBBFBBLLR\n" +
                "BFBFBFFLRL\n" +
                "FFBBFFBLRL\n" +
                "FBBBFBFRRL\n" +
                "FFFBBFBRLL\n" +
                "BBFFBFFLRL\n" +
                "FBFBFFBLLL\n" +
                "FBBFBBFRRR\n" +
                "FFBFFFFLRR\n" +
                "FBFFBFFRLR\n" +
                "FBBBFFBRLR\n" +
                "BBFFBFFLLL\n" +
                "BBFBBBBLLL\n" +
                "FBFBBFFRLL\n" +
                "BFBBBBFLRR\n" +
                "FBFFBBFLRR\n" +
                "BFFBBFBLRR\n" +
                "BBFFFBFRLL\n" +
                "BBBFFBFLRL\n" +
                "BBFFBFBRRR\n" +
                "BBBFBFBLLR\n" +
                "FBFBFBBLLL\n" +
                "BBFBFFFRLR\n" +
                "BFFBFFFRLR\n" +
                "BFBBBFFLRL\n" +
                "FFBBFFFRRR\n" +
                "FFBBBFFRLR\n" +
                "BFBFBFFLLL\n" +
                "FBBFFBBLLL\n" +
                "FBBFBBBRLL\n" +
                "FFBBBBBLRL\n" +
                "FFFBBBBRLL\n" +
                "BFBBBBFRRL\n" +
                "FBBFFBBRRR\n" +
                "BFBBBBBLRR\n" +
                "BFBBFBFRRR\n" +
                "BBFFBBBRLL\n" +
                "BBFBFBBLRR\n" +
                "BFBFFBBRRR\n" +
                "FBFBBFFLRL\n" +
                "FBBBFFFLLR\n" +
                "BFBBBFFRLR\n" +
                "BFFBBBBLRR\n" +
                "FFBBBFFRRR\n" +
                "FBBBFBFRRR\n" +
                "FFFBBBFRRL\n" +
                "BFBFBBFRRL\n" +
                "FFBBFBBLRR\n" +
                "FFFBFBFLLL\n" +
                "FBBFBBFRLL\n" +
                "BBFFFBBLRL\n" +
                "FFFBBBFLRL\n" +
                "FBFFFBBRRL\n" +
                "FBBBBFFRRL\n" +
                "FFBBFBBRLL\n" +
                "BBFFBBFLLL\n" +
                "BFFBFFFLLL\n" +
                "FFBBBFFLRR\n" +
                "BFBBBFBRLR\n" +
                "BFFBBBFRLR\n" +
                "FFFBBFFLLL\n" +
                "FFBFFBBLRL\n" +
                "FBFFBFFRRR\n" +
                "BFBBBFFRLL\n" +
                "FBBFFBBRLR\n" +
                "BFFBBBBLRL\n" +
                "BBFFFFFLRR\n" +
                "BBFBFFFLLL\n" +
                "FBFFFFFLLR\n" +
                "FBBBBFFLLR\n" +
                "BBFFFBFLRL\n" +
                "FBBFBFBRLR\n" +
                "FBBFBFBRRL\n" +
                "FFBBFFFRLR\n" +
                "FFBFBBBLRL\n" +
                "FFBBBBBRLR\n" +
                "BBFFFBFLRR\n" +
                "BFBBFFFRRL\n" +
                "BBFBFBFLRL\n" +
                "FBBBBBBRLL\n" +
                "FBBFBFFLRL\n" +
                "FBFBFBFLRL\n" +
                "BFBFBFFRRL\n" +
                "BFBBFFBRRR\n" +
                "FBFFFBFLLR\n" +
                "FBBBFFFLRL\n" +
                "BFBBFFBLLR\n" +
                "FFBFFFFLLL\n" +
                "BFBBFFFLRR\n" +
                "FBBFBFFLLR\n" +
                "BBBFFBBRLR\n" +
                "FFBFBBBLLR\n" +
                "FBFBFFBRRL\n" +
                "FFBBFBFLLR\n" +
                "BFFBFBFRLR\n" +
                "BFFBFFBLLR\n" +
                "BBBFBFFLLL\n" +
                "FFBFFBFLLR\n" +
                "FFFBBBBLRR\n" +
                "FFFBFFBRRL\n" +
                "FBBBFFFRRL\n" +
                "BBFFFBBRRL\n" +
                "BBFBBFBLRR\n" +
                "BBFFBBBRRL\n" +
                "BBFBFBBRLL\n" +
                "BFFFFFFRLL\n" +
                "BFFBFFFLRL\n" +
                "BFFFFBFRRR\n" +
                "BFFFBFFLRL\n" +
                "BFBFFBBLRR\n" +
                "FFBBFBBRLR\n" +
                "BFBBBBBRRR\n" +
                "BFFBBFFRRL\n" +
                "FFBFFFBLLL\n" +
                "FBBFBBFRLR\n" +
                "BBFFBBBLLR\n" +
                "FFFBBFFRRL\n" +
                "FFFBBFBLRR\n" +
                "FBFBFBBLRR\n" +
                "FBBBFFFLLL\n" +
                "FFBFBFBLLR\n" +
                "BFBBFFBRLR\n" +
                "BFFFFBBLLL\n" +
                "BFBBBBFLRL\n" +
                "FBBBBBBLLR\n" +
                "BFFFFBBRRR\n" +
                "BBFFFBBLLR\n" +
                "FFBBBFFLLR\n" +
                "FFFBFBFRRL\n" +
                "BFFFFBFRLL\n" +
                "BFFBBBBRLR\n" +
                "FBFFBFBLLR\n" +
                "FBBFFBBLRR\n" +
                "BBBFFBBLRR\n" +
                "BFFBFBBRLL\n" +
                "BFBFBFFLLR\n" +
                "FFBFBFBRRL\n" +
                "BBFFBBFRRR\n" +
                "FFBFBFBRLR\n" +
                "FBBFFFFLLR\n" +
                "FBBFBFFRRL\n" +
                "FBFFBBFRRR\n" +
                "FBBBBFBLRL";
        String[] split = in.split("\n");
        int max = Integer.MIN_VALUE;
        int min = Integer.MAX_VALUE;
        ArrayList<Integer> list = new ArrayList<>();
        for (String input : split) {
            StringBuilder rowBuilder = new StringBuilder();
            StringBuilder columnBuilder = new StringBuilder();
            for (int i = 0; i < 7; i++) rowBuilder.append(input.charAt(i));
            for (int i = 7; i < 10; i++) columnBuilder.append(input.charAt(i));
            String row = rowBuilder.toString();
            String column = columnBuilder.toString();
            list.add(findSeat(row, column));
        }
        for (Integer integer : list) {
            max = Math.max(integer, max);
            min = Math.min(integer, min);
        }

        int[] ints = new int[max + 1];
        for (Integer integer : list) {
            ints[integer] = integer;
        }

        for (int i = min; i < ints.length; i++) {
            if (ints[i] == 0) System.out.println(i);
        }
    }

    private static int findSeat(String rowPattern, String columnPattern) {
        int row = stringPatternToInteger(rowPattern);
        int column = stringPatternToInteger(columnPattern);
        return (row * 8) + column;
    }


    private static int stringPatternToInteger(String rowPattern) {
        int decimal = 0;
        for (char c : rowPattern.toCharArray()) {
            decimal = decimal * 2;
            if (c == 'B') decimal = decimal + 1;
            if (c == 'R') decimal = decimal + 1;
        }
        return decimal;
    }
}
